[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["taskCloud"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.black]
line-length = 120
target-version = ['py39']
skip-string-normalization = true